/*
 * SPDX-FileCopyrightText: Copyright (c) 2023-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include <assert.h>

#include <complex>
#include <iostream>
#include <unordered_map>
#include <vector>

#include <cutensor.h>
#include "utils.cuh"

int main()
try
{
    typedef std::complex<float> TypeA;
    typedef std::complex<float> TypeB;
    typedef std::complex<float> TypeC;
    typedef std::complex<float> TypeScalar;

    auto alpha = TypeScalar(1.1, 0.0);
    auto beta  = TypeScalar(0.0, 0.0);

    cudaDataType_t typeA = CUDA_C_32F;
    cudaDataType_t typeB = CUDA_C_32F;
    cudaDataType_t typeC = CUDA_C_32F;
    cutensorComputeDescriptor_t descCompute = CUTENSOR_COMPUTE_DESC_3XTF32;

    /**********************
     * Computing: C_{0,1,2,3,4,6,8,9,25,26,10,12,14,27,15,28,17,19,29,20,21,30,23,24} =
     *                   \alpha A_{0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24}
     *                   B_{25,26,27,28,29,30,5,7,11,13,16,18,22}
     *                   + \beta C_{0,1,2,3,4,6,8,9,25,26,10,12,14,27,15,28,17,19,29,20,21,30,23,24}
     **********************/

    /* ***************************** */

    // Create vector of modes
    std::vector<int> modeC{0,1,2,3,4,6,8,9,25,26,10,12,14,27,15,28,17,19,29,20,21,30,23,24};
    std::vector<int> modeA{0,2,1,4,3,5,6,7,8,9,10,11,12,13,14,15,16,17,18,20,19,21,22,23,24};
    std::vector<int> modeB{25,26,27,28,29,30,5,7,11,13,16,18,22};
    int nmodeA = modeA.size();
    int nmodeB = modeB.size();
    int nmodeC = modeC.size();

    // Extents
    std::unordered_map<int, int64_t> extent;
    for (auto i = 0; i <= 30; i++)
        extent[i] = 2;

    // Create a vector of extents for each tensor
    std::vector<int64_t> extentC;
    for (auto mode : modeC)
        extentC.push_back(extent[mode]);
    std::vector<int64_t> extentA;
    for (auto mode : modeA)
        extentA.push_back(extent[mode]);
    std::vector<int64_t> extentB;
    for (auto mode : modeB)
        extentB.push_back(extent[mode]);

    /**********************
     * Allocating data
     **********************/

    // Number of elements of each tensor
    size_t elementsA = 1;
    for (auto mode : modeA)
        elementsA *= extent[mode];
    size_t elementsB = 1;
    for (auto mode : modeB)
        elementsB *= extent[mode];
    size_t elementsC = 1;
    for (auto mode : modeC)
        elementsC *= extent[mode];

    // Size in bytes
    size_t sizeA = sizeof(TypeA) * elementsA;
    size_t sizeB = sizeof(TypeB) * elementsB;
    size_t sizeC = sizeof(TypeC) * elementsC;
    printf("Total memory: %.2f GiB\n", (sizeA + sizeB + sizeC)/1024./1024./1024);

    auto A_d = cuda_alloc     <TypeA>(elementsA); 
    auto B_d = cuda_alloc     <TypeB>(elementsB); 
    auto C_d = cuda_alloc     <TypeC>(elementsC); 
   
    auto A   = cuda_host_alloc<TypeA>(elementsA); 
    auto B   = cuda_host_alloc<TypeB>(elementsB); 
    auto C   = cuda_host_alloc<TypeC>(elementsC); 

    /*******************
     * Initialize data
     *******************/

    // Random data.
    std::generate(A.get(),A.get()+elementsA, randomgen<TypeA>() );
    std::generate(B.get(),B.get()+elementsB, randomgen<TypeB>() );
    std::generate(C.get(),C.get()+elementsC, randomgen<TypeC>() );

    // Copy to device
    handle_error(cudaMemcpy(A_d.get(), A.get(), sizeA, cudaMemcpyHostToDevice));
    handle_error(cudaMemcpy(B_d.get(), B.get(), sizeB, cudaMemcpyHostToDevice));
    handle_error(cudaMemcpy(C_d.get(), C.get(), sizeC, cudaMemcpyHostToDevice));

    const uint32_t kAlignment = 128; // Alignment of the global-memory device pointers (bytes)
    assert(uintptr_t(A_d.get()) % kAlignment == 0);
    assert(uintptr_t(B_d.get()) % kAlignment == 0);
    assert(uintptr_t(C_d.get()) % kAlignment == 0);

    /*************************
     * cuTENSOR
     *************************/ 

    cutensorHandle_t handle;
    handle_error(cutensorCreate(&handle));
    auto guardHandle = finally( [&handle]() { cutensorDestroy(handle); } );

    // Read kernel cache from file (if the file was generated by a prior execution)
    auto readKernelCacheStatus = cutensorReadKernelCacheFromFile(handle, "kernelCache.bin");

    if (readKernelCacheStatus == CUTENSOR_STATUS_IO_ERROR)
        printf("No kernel cache found. It will be generated before the end of this execution.\n");
    else if (readKernelCacheStatus == CUTENSOR_STATUS_SUCCESS)
        printf("Kernel cache found and read successfully.\n");
    else if (readKernelCacheStatus == CUTENSOR_STATUS_NOT_SUPPORTED)
    {
        printf("JIT not supported (rerun with CUTENSOR_LOG_LEVEL=5 for details).\n");
        return 0;
    }
    else
    {
        handle_error(readKernelCacheStatus);
    }

    /**********************
     * Create Tensor Descriptors
     **********************/

    cutensorTensorDescriptor_t descA;
    handle_error(cutensorCreateTensorDescriptor(handle,
                                                &descA,
                                                nmodeA,
                                                extentA.data(),
                                                NULL,/*stride*/
                                                typeA, kAlignment));
    auto guardDescA = finally( [&descA]() { cutensorDestroyTensorDescriptor(descA); } );

    cutensorTensorDescriptor_t descB;
    handle_error(cutensorCreateTensorDescriptor(handle,
                                                &descB,
                                                nmodeB,
                                                extentB.data(),
                                                NULL,/*stride*/
                                                typeB, kAlignment));
    auto guardDescB = finally( [&descB]() { cutensorDestroyTensorDescriptor(descB); } );

    cutensorTensorDescriptor_t descC;
    handle_error(cutensorCreateTensorDescriptor(handle,
                                                &descC,
                                                nmodeC,
                                                extentC.data(),
                                                NULL,/*stride*/
                                                typeC, kAlignment));
    auto guardDescC = finally( [&descC]() { cutensorDestroyTensorDescriptor(descC); } );

    /*******************************
     * Create Contraction Descriptor
     *******************************/

    cutensorOperationDescriptor_t desc;
    handle_error(cutensorCreateContraction(handle, 
                                           &desc,
                                           descA, modeA.data(), /* unary operator A*/CUTENSOR_OP_IDENTITY,
                                           descB, modeB.data(), /* unary operator B*/CUTENSOR_OP_IDENTITY,
                                           descC, modeC.data(), /* unary operator C*/CUTENSOR_OP_IDENTITY,
                                           descC, modeC.data(),
                                           descCompute));
    auto guardDesc = finally( [&desc]() { cutensorDestroyOperationDescriptor(desc); } );

    /*****************************
     * Optional (but recommended): ensure that the scalar type is correct.
     *****************************/

    cudaDataType_t scalarType;
    handle_error(cutensorOperationDescriptorGetAttribute(handle,
                                                         desc,
                                                         CUTENSOR_OPERATION_DESCRIPTOR_SCALAR_TYPE,
                                                         (void*)&scalarType,
                                                         sizeof(scalarType)));

    assert(scalarType == CUDA_C_32F);

    /**************************
    * Set the algorithm to use -- without just-in-time compilation
    ***************************/

    const cutensorAlgo_t algo = CUTENSOR_ALGO_GETT;

    cutensorPlanPreference_t planPref;
    handle_error(cutensorCreatePlanPreference(handle,
                                              &planPref,
                                              algo,
                                              CUTENSOR_JIT_MODE_NONE));
    auto guardPlanPref = finally( [&planPref]() { cutensorDestroyPlanPreference(planPref); } );

    /**********************
     * Query workspace estimate
     **********************/

    uint64_t workspaceSizeEstimate = 0;
    const cutensorWorksizePreference_t workspacePref = CUTENSOR_WORKSPACE_DEFAULT;
    handle_error(cutensorEstimateWorkspaceSize(handle,
                                               desc,
                                               planPref,
                                               workspacePref,
                                               &workspaceSizeEstimate));

    /**************************
     * Create Contraction Plan -- without just-in-time compilation
     **************************/

    cutensorPlan_t plan;
    handle_error(cutensorCreatePlan(handle,
                                    &plan,
                                    desc,
                                    planPref,
                                    workspaceSizeEstimate));
    auto guardPlan = finally( [&plan]() { cutensorDestroyPlan(plan); } );

    /**************************
     * Optional: Query information about the created plan
     **************************/

    // query actually used workspace
    uint64_t actualWorkspaceSize = 0;
    handle_error(cutensorPlanGetAttribute(handle,
                                              plan,
                                              CUTENSOR_PLAN_REQUIRED_WORKSPACE,
                                              &actualWorkspaceSize,
                                              sizeof(actualWorkspaceSize)));

    // At this point the user knows exactly how much memory is need by the operation and
    // only the smaller actual workspace needs to be allocated
    assert(actualWorkspaceSize <= workspaceSizeEstimate);

    auto work = cuda_alloc<char>(actualWorkspaceSize);
    assert(uintptr_t(work.get()) % 128 == 0); // workspace must be aligned to 128 byte-boundary

    /**********************
     * Execute the tensor contraction
     **********************/

    cudaStream_t stream;
    handle_error(cudaStreamCreate(&stream));
    auto guardStream = finally( [&stream]() { cudaStreamDestroy(stream); } );

    double minTimeCUTENSOR = 1e100;
    for (int i=0; i < 3; ++i)
    {
        handle_error(cudaMemcpy(C_d.get(), C.get(), sizeC, cudaMemcpyHostToDevice));

        // Set up timing
        GPUTimer timer(stream);
        handle_error(cutensorContract(handle,
                                      plan,
                                      (void*) &alpha, A_d.get(), B_d.get(),
                                      (void*) &beta,  C_d.get(), C_d.get(),
                                      work.get(), actualWorkspaceSize, stream));

        // Synchronize and measure timing
        auto time = timer.seconds(stream);

        minTimeCUTENSOR = (minTimeCUTENSOR < time) ? minTimeCUTENSOR : time;
    }

    /*************************/

    /**************************
    * Set the algorithm to use -- with just-in-time compilation
    ***************************/

    cutensorPlanPreference_t planPrefJit;
    handle_error(cutensorCreatePlanPreference(handle,
                                              &planPrefJit,
                                              algo,
                                              CUTENSOR_JIT_MODE_DEFAULT));
    auto guardPlanPrefJit = finally( [&planPrefJit]() { cutensorDestroyPlanPreference(planPrefJit); } );

    /**********************
     * Query workspace estimate
     **********************/

    uint64_t workspaceSizeEstimateJit = 0;
    const cutensorWorksizePreference_t workspacePrefJit = CUTENSOR_WORKSPACE_DEFAULT;
    handle_error(cutensorEstimateWorkspaceSize(handle,
                                               desc,
                                               planPrefJit,
                                               workspacePrefJit,
                                               &workspaceSizeEstimateJit));

    /**************************
     * Create Contraction Plan -- with just-in-time compilation
     **************************/

    cutensorPlan_t planJit;
    CPUTimer jitPlanTimer;
    jitPlanTimer.start();
    // This is where the kernel is actually compiled
    handle_error(cutensorCreatePlan(handle,
                                    &planJit,
                                    desc,
                                    planPrefJit,
                                    workspaceSizeEstimateJit));
    auto guardPlanJit = finally( [&planJit]() { cutensorDestroyPlan(planJit); } );
    auto jitPlanTime = jitPlanTimer.seconds();

    /**************************
     * Optional: Query information about the created plan
     **************************/

    // query actually used workspace
    uint64_t actualWorkspaceSizeJit = 0;
    handle_error(cutensorPlanGetAttribute(handle,
                                              planJit,
                                              CUTENSOR_PLAN_REQUIRED_WORKSPACE,
                                              &actualWorkspaceSizeJit,
                                              sizeof(actualWorkspaceSizeJit)));

    // At this point the user knows exactly how much memory is need by the operation and
    // only the smaller actual workspace needs to be allocated
    assert(actualWorkspaceSizeJit <= workspaceSizeEstimateJit);

    void *workJit = nullptr;
    handle_error(cudaMalloc(&workJit, actualWorkspaceSizeJit));
    auto guardWorkJit = finally( [&workJit]() { cudaFree(workJit); } );
    assert(uintptr_t(workJit) % 128 == 0); // workspace must be aligned to 128 byte-boundary

    /**********************
     * Execute the tensor contraction using the JIT compiled kernel
     **********************/

    double minTimeCUTENSORJit = 1e100;
    for (int i=0; i < 3; ++i)
    {
        handle_error(cudaMemcpy(C_d.get(), C.get(), sizeC, cudaMemcpyHostToDevice));

        // Set up timing
        GPUTimer timer(stream);
        handle_error(cutensorContract(handle,
                                      planJit,
                                      (void*) &alpha, A_d.get(), B_d.get(),
                                      (void*) &beta,  C_d.get(), C_d.get(),
                                      workJit, actualWorkspaceSizeJit, stream));

        // Synchronize and measure timing
        auto time = timer.seconds(stream);

        minTimeCUTENSORJit = (minTimeCUTENSORJit < time) ? minTimeCUTENSORJit : time;
    }

    /*************************/

    float flops;
    handle_error(cutensorOperationDescriptorGetAttribute(handle,
                                                         desc,
                                                         CUTENSOR_OPERATION_DESCRIPTOR_FLOPS,
                                                         (void*)&flops,
                                                         sizeof(flops)));
    auto gflops = flops / 1e9;
    auto gflopsPerSec = gflops / minTimeCUTENSOR;
    auto gflopsPerSecJit = gflops / minTimeCUTENSORJit;

    printf("cuTENSOR    : %6.0f GFLOPs/s\n", gflopsPerSec);
    printf("cuTENSOR JIT: %6.0f GFLOPs/s\n", gflopsPerSecJit);
    printf("Speedup: %.1fx\n", gflopsPerSecJit / gflopsPerSec);
    printf("JIT Compilation time: %.1f seconds ", jitPlanTime);
    if (readKernelCacheStatus == CUTENSOR_STATUS_SUCCESS)
        printf("(Kernel cache file was read successfully; Compilation was not required)\n");
    else
        printf("\n");

    // Write kernel cache to file
    handle_error(cutensorWriteKernelCacheToFile(handle, "kernelCache.bin"));
    printf("Kernel cache written to file. Will be read in next execution.\n");

    printf("Successful completion\n");
    return EXIT_SUCCESS;
}
catch ( std::exception &ex )
{
    std::cerr << "Exception caught! Exiting." << std::endl;
    std::cerr << ex.what() << std::endl;
    return EXIT_FAILURE;
}
catch ( ... )
{
    std::cerr << "Unknown exception caught! Exiting." << std::endl;
    return EXIT_FAILURE;
}

