/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// This example demonstrates using NVRTC with pre-generated LTO artifacts.
// It uses:
// 1. Pre-generated lto_database.hpp.inc header (generated by lto_helper)
// 2. Pre-generated LTOIR files on disk (generated by lto_helper)
// 3. query_database to find the best implementation from the pre-generated database
// 4. NVRTC to compile the kernel and nvJitLink to link with pre-generated LTOIRs

#include <vector>
#include <iostream>
#include <fstream>
#include <chrono>
#include <string>

#include <nvrtc.h>
#include <nvJitLink.h>
#include <cuda.h>
#include <cuda_runtime_api.h>

#define CUFFTDX_ENABLE_RUNTIME_DATABASE
#include <cufftdx/utils.hpp>

#include "../common/common.hpp"
#include "../common/common_nvrtc.hpp"
#include "../common/common_nvjitlink.hpp"

// Include pre-generated LTO database header
#include "lto_database.hpp.inc"

// Stringify macro for passing artifacts directory path
#define STRINGIFY(x) STRINGIFY_HELPER(x)
#define STRINGIFY_HELPER(x) #x

const char* test_kernel = R"kernel(
using namespace cufftdx;

// FFT Operators
using size_desc = Size<FFT_SIZE>;
using dir_desc  = Direction<fft_direction::forward>;
using type_c2c  = Type<fft_type::c2c>;
using fpb_desc = FFTsPerBlock<FFT_FPB>;
using FFT = decltype(Block() + size_desc() + dir_desc() + type_c2c() + Precision<float>() + SM<FFT_SM>() + ElementsPerThread<FFT_EPT>() + fpb_desc() + experimental::CodeType<experimental::code_type::ltoir>());

inline __device__ unsigned int batch_offset(const unsigned int local_fft_id,
                                            const unsigned int ffts_per_block = blockDim.y) {
    unsigned int global_fft_id = ffts_per_block == 1 ? blockIdx.x : (blockIdx.x * ffts_per_block + local_fft_id);
    return cufftdx::size_of<FFT>::value * global_fft_id;
}

extern "C" __global__ void test_kernel(typename FFT::value_type* fft_data)
{
  typename FFT::value_type thread_data[FFT::storage_size];

  const unsigned int offset = batch_offset(threadIdx.y, FFT::ffts_per_block);
  constexpr unsigned int stride = FFT::stride;
  unsigned int index = offset + threadIdx.x;
  for (unsigned int i = 0; i < FFT::elements_per_thread; i++) {
    if ((i * stride + threadIdx.x) < cufftdx::size_of<FFT>::value) {
        thread_data[i] = fft_data[index];
        index += stride;
    }
  }

  extern __shared__ FFT::value_type shared_mem[];
  FFT().execute(thread_data, shared_mem);

  index = offset + threadIdx.x;
  for (unsigned int i = 0; i < FFT::elements_per_thread; i++) {
    if ((i * stride + threadIdx.x) < cufftdx::size_of<FFT>::value) {
        fft_data[index] = thread_data[i];
        index += stride;
    }
  }
}
)kernel";

// Directory containing the running executable, resolved from argv[0] in main().
static std::string executable_dir;

// Returns the parent directory of a path, or empty if there's no separator.
std::string parent_dir(const std::string& path) {
    auto pos = path.find_last_of('/');
    return (pos != std::string::npos) ? path.substr(0, pos) : "";
}

// Returns true if a file can be opened for reading.
bool file_exists(const std::string& path) {
    return std::ifstream(path).good();
}

// Helper function to read a file into a vector. Returns empty vector on failure.
std::vector<char> read_file(const std::string& path) {
    std::ifstream file(path, std::ios::binary | std::ios::ate);
    if (!file.is_open())
        return {};

    std::streamsize size = file.tellg();
    file.seekg(0, std::ios::beg);

    std::vector<char> buffer(size);
    if (!file.read(buffer.data(), size))
        return {};

    return buffer;
}

template<unsigned int Arch>
int nvrtc_lto_query_database_helper() {
    // FFT configuration matching introduction_lto_cases.csv: size=128, direction=forward, block
    static constexpr unsigned int fft_size = 128;
    constexpr unsigned int arch = static_cast<unsigned int>(Arch);

    using value_type = float2;

    // Get current device
    int current_device;
    CUDA_CHECK_AND_EXIT(cudaGetDevice(&current_device));

    // Resolve artifacts directory: prefer path relative to executable (works after
    // install / CI extraction), fall back to the absolute build-tree path.
    std::string artifacts_dir;
    if (!executable_dir.empty()) {
        std::string candidate = executable_dir + "/" + STRINGIFY(LTO_ARTIFACTS_RELDIR);
        if (file_exists(candidate + "/lto_database.hpp.inc")) {
            artifacts_dir = candidate;
        }
    }
    if (artifacts_dir.empty()) {
        artifacts_dir = STRINGIFY(LTO_ARTIFACTS_DIR);
    }
    std::cout << "Loading LTO artifacts from: " << artifacts_dir << std::endl;

    // Query the pre-generated database for the best LTO implementation
    // The database is already included via lto_database.hpp.inc
    auto query_result = cufftdx::experimental::utils::query_database(
        fft_size,
        cufftdx::fft_direction::forward,
        cufftdx::fft_type::c2c,
        arch,
        cufftdx::utils::execution_type::block,
        cufftdx::precision::f32,
        0,         // fft_ept: 0 means use heuristic
        0,         // fpb
        {0, 0, 0}, // block_dim
        cufftdx::complex_layout::natural,
        cufftdx::real_mode::normal,
        cufftdx::experimental::query_code_type::ltoir_offline);

    if (!query_result.has_value()) {
        std::cout << "No offline LTO implementation found in pre-generated database for size=" << fft_size
                  << " arch=" << arch
                  << "; empty query result is expected when this cuFFT database does not support offline LTO query." << std::endl;
        return 0;
    }

    const auto& impl = query_result.value();
    std::cout << "query_database(ltoir): Found implementation:" << std::endl;
    std::cout << "  block_dim=(" << impl.block_dim_x << "," << impl.block_dim_y << "," << impl.block_dim_z << ")"
              << " ept=" << impl.elements_per_thread
              << " fpb=" << impl.ffts_per_block
              << " shared_mem=" << impl.shared_memory_size
              << " storage_size=" << impl.storage_size
              << std::endl;

    unsigned int fft_ept = impl.elements_per_thread;
    unsigned int ffts_per_block = impl.ffts_per_block;
    dim3         block_dim(impl.block_dim_x, impl.block_dim_y, impl.block_dim_z);
    unsigned int shared_memory_size = impl.shared_memory_size;

    // Load individual pre-generated LTOIR/fatbin files from disk (generated by lto_helper).
    // lto_helper writes files named cufft_generated_{i}.ltoir or cufft_generated_{i}.fatbin.
    std::vector<std::vector<char>> ltoir_blobs;
    // Upper bound on artifact count to avoid directory listing (which requires <filesystem> / POSIX APIs).
    // lto_helper names files sequentially (cufft_generated_0, 1, ...) so we just probe until a gap.
    constexpr unsigned max_lto_artifacts = 1024;
    for (unsigned i = 0; i < max_lto_artifacts; ++i) {
        std::string base = artifacts_dir + "/cufft_generated_" + std::to_string(i);
        auto        data = read_file(base + ".ltoir");
        if (data.empty())
            data = read_file(base + ".fatbin");
        if (data.empty())
            break;
        ltoir_blobs.push_back(std::move(data));
    }
    if (ltoir_blobs.empty()) {
        std::cerr << "No .ltoir or .fatbin files found in: " << artifacts_dir << std::endl;
        std::exit(1);
    } else {
        std::cout << "Loaded " << ltoir_blobs.size() << " LTOIR/fatbin files from: " << artifacts_dir << std::endl;
    }

    // Read the database header content to include in NVRTC source
    auto lto_db_data = read_file(artifacts_dir + "/lto_database.hpp.inc");
    if (lto_db_data.empty()) {
        std::cerr << "Failed to read database header" << std::endl;
        std::exit(1);
    }
    std::string lto_db(lto_db_data.begin(), lto_db_data.end());

    // Build CUDA source code. Plug in the database header after cufftdx.hpp inclusion.
    std::string dx_source_code;
    dx_source_code.append("#include <cufftdx.hpp>\n");
    dx_source_code.append(lto_db);
    dx_source_code.append(test_kernel);

    // Create a program
    nvrtcProgram prog;
    NVRTC_SAFE_CALL(nvrtcCreateProgram(&prog,                  // prog
                                       dx_source_code.c_str(), // buffer
                                       "test_kernel.cu",       // name
                                       0,                      // numHeaders
                                       NULL,                   // headers
                                       NULL));                 // includeNames

    // Prepare compilation options
    std::vector<const char*> opts = {
        "--std=c++17",
        "--device-as-default-execution-space"};
    // Parse cuFFTDx include dirs
    std::vector<std::string> cufftdx_include_dirs = example::nvrtc::get_cufftdx_include_dirs();
    // Add cuFFTDx include dirs to opts
    for (auto& d : cufftdx_include_dirs) {
        opts.push_back(d.c_str());
    }

    // Add FFT_SIZE definition to opts
    std::string fft_size_definition = "-DFFT_SIZE=" + std::to_string(fft_size);
    opts.push_back(fft_size_definition.c_str());

    // Add FFT_EPT definition to opts
    std::string fft_ept_definition = "-DFFT_EPT=" + std::to_string(fft_ept);
    opts.push_back(fft_ept_definition.c_str());

    // Add FFT_FPB definition to opts
    std::string fft_fpb_definition = "-DFFT_FPB=" + std::to_string(ffts_per_block);
    opts.push_back(fft_fpb_definition.c_str());

    // Add GPU_ARCHITECTURE definition to opts
    std::string gpu_architecture_definition = "-DFFT_SM=" + std::to_string(Arch);
    opts.push_back(gpu_architecture_definition.c_str());

    // Add gpu-architecture to opts
    std::string nvrtc_gpu_architecture_option = example::nvrtc::get_device_architecture_option(current_device);
    opts.push_back(nvrtc_gpu_architecture_option.c_str());

    // Add flags for LTO compilation
    opts.push_back("-dlto");
    opts.push_back("--relocatable-device-code=true");

    const auto  compile_start = std::chrono::high_resolution_clock::now();
    nvrtcResult compileResult = nvrtcCompileProgram(prog,                          // prog
                                                    static_cast<int>(opts.size()), // numOptions
                                                    opts.data());                  // options
    std::cout << "NVRTC compile time (ms): "
              << (double)std::chrono::duration_cast<std::chrono::microseconds>(
                     std::chrono::high_resolution_clock::now() - compile_start)
                         .count() /
                     1e3
              << "\n";

    // Obtain compilation log from the program
    if (compileResult != NVRTC_SUCCESS) {
        example::nvrtc::print_program_log(prog);
        std::exit(1);
    }

    // Obtain LTOIR from the program.
    size_t ltoir_size;
    NVRTC_SAFE_CALL(nvrtcGetLTOIRSize(prog, &ltoir_size));
    auto ltoir = std::vector<char>(ltoir_size);
    NVRTC_SAFE_CALL(nvrtcGetLTOIR(prog, ltoir.data()));

    // Destroy the program.
    NVRTC_SAFE_CALL(nvrtcDestroyProgram(&prog));

    // Load the generated LTOIR and the pre-generated LTOIRs and link them together
    nvJitLinkHandle          handle;
    std::vector<const char*> link_opts;
    link_opts.push_back("-dlto");

    std::string nvjitlink_gpu_architecture_option = example::nvjitlink::get_device_architecture_option(current_device);
    link_opts.push_back(nvjitlink_gpu_architecture_option.c_str());

    NVJITLINK_SAFE_CALL(handle, nvJitLinkCreate(&handle, static_cast<int>(link_opts.size()), link_opts.data()));
    NVJITLINK_SAFE_CALL(handle, nvJitLinkAddData(handle, NVJITLINK_INPUT_ANY, ltoir.data(), ltoir_size, "nvrtc_ltoir"));

    // Add pre-generated LTOIR/fatbin files individually
    for (unsigned i = 0; i < ltoir_blobs.size(); i++) {
        NVJITLINK_SAFE_CALL(handle, nvJitLinkAddData(handle, NVJITLINK_INPUT_ANY, ltoir_blobs[i].data(), ltoir_blobs[i].size(), "cufft_generated_ltoir"));
    }

    const auto link_start = std::chrono::high_resolution_clock::now();
    NVJITLINK_SAFE_CALL(handle, nvJitLinkComplete(handle));
    std::cout << "NVJITLINK link time (ms): "
              << (double)std::chrono::duration_cast<std::chrono::microseconds>(
                     std::chrono::high_resolution_clock::now() - link_start)
                         .count() /
                     1e3
              << "\n";

    // Obtain linked Cubin
    size_t cubin_size;
    NVJITLINK_SAFE_CALL(handle, nvJitLinkGetLinkedCubinSize(handle, &cubin_size));
    auto cubin = std::vector<char>(cubin_size);
    NVJITLINK_SAFE_CALL(handle, nvJitLinkGetLinkedCubin(handle, cubin.data()));
    NVJITLINK_SAFE_CALL(handle, nvJitLinkDestroy(&handle));

    // Load the Cubin and get a handle to the test_kernel
    CUdevice   cuDevice;
    CUcontext  context;
    CUmodule   module;
    CUfunction kernel;
    CU_CHECK_AND_EXIT(cuInit(0));
    CU_CHECK_AND_EXIT(cuDeviceGet(&cuDevice, current_device));
#if defined(CUDA_VERSION) && CUDA_VERSION >= 13000
    CU_CHECK_AND_EXIT(cuCtxCreate(&context, (CUctxCreateParams*)0, 0, cuDevice));
#else
    CU_CHECK_AND_EXIT(cuCtxCreate(&context, 0, cuDevice));
#endif
    CU_CHECK_AND_EXIT(cuModuleLoadDataEx(&module, cubin.data(), 0, 0, 0));
    CU_CHECK_AND_EXIT(cuModuleGetFunction(&kernel, module, "test_kernel"));

    // Generate input for execution
    const size_t total_size = fft_size * ffts_per_block;
    value_type* fft_data;
    CUDA_CHECK_AND_EXIT(cudaMallocManaged(&fft_data, total_size * sizeof(value_type)));

    for (size_t b = 0; b < ffts_per_block; b++) {
        for (size_t i = 0; i < fft_size; i++) {
            fft_data[b * fft_size + i].x = float(i);
            fft_data[b * fft_size + i].y = 0;
        }
    }

    // Execute test_kernel
    void* args[] = {&fft_data};
    CU_CHECK_AND_EXIT(cuLaunchKernel(kernel,
                                     1, // number of blocks
                                     1,
                                     1,
                                     block_dim.x, // number of threads
                                     block_dim.y,
                                     block_dim.z,
                                     shared_memory_size, // shared memory size
                                     NULL,               // NULL stream
                                     args,
                                     0));
    CU_CHECK_AND_EXIT(cuCtxSynchronize());

    // Validate results before destroying context
    float sum = (fft_size * (fft_size - 1)) / 2.0f;
    if (std::abs(fft_data[0].x - sum) > 0.01f) {
        std::cout << "[nvrtc_query_database_fft_block_lto] Failed" << std::endl;
        CUDA_CHECK_AND_EXIT(cudaFree(fft_data));
        CU_CHECK_AND_EXIT(cuModuleUnload(module));
        CU_CHECK_AND_EXIT(cuCtxDestroy(context));
        return 1;
    }
    std::cout << "[nvrtc_query_database_fft_block_lto] Passed" << std::endl;

    // Release resources
    CUDA_CHECK_AND_EXIT(cudaFree(fft_data));
    CU_CHECK_AND_EXIT(cuModuleUnload(module));
    CU_CHECK_AND_EXIT(cuCtxDestroy(context));
    return 0;
}

template<unsigned int Arch>
struct nvrtc_lto_query_database_helper_functor {
    int operator()() { return nvrtc_lto_query_database_helper<Arch>(); }
};

int main(int, char* argv[]) {
    executable_dir = parent_dir(argv[0]);
    return example::sm_runner<nvrtc_lto_query_database_helper_functor>();
}
